// --- 1. Database dei Prompt (Static Data) ---
const PROMPTS_DATA = [
    // --- FRONTEND ---
    { id: 1, title: "Refactoring React Component", category: "Frontend", tags: ["React", "Clean Code"], description: "Ottimizza un componente React esistente per performance e leggibilità.", content: "Agisci come un Senior React Developer. Esegui un refactoring del codice seguente seguendo le best practices React 18+.\nObiettivi:\n1. Converti in Functional Component con Hooks.\n2. Usa useMemo/useCallback per le performance.\n3. Tipizzazione TypeScript rigorosa.\n\nCodice:\n[INCOLLA CODICE]" },
    { id: 2, title: "Tailwind CSS Converter", category: "Frontend", tags: ["CSS", "Tailwind"], description: "Converti CSS standard o stili inline in classi utility Tailwind.", content: "Converti il seguente CSS/SASS in classi utility Tailwind CSS. Evita valori arbitrari (es. `p-[16px]`) e usa la scala standard. Gestisci hover e focus.\n\nCSS:\n[INCOLLA CSS]" },
    { id: 3, title: "Accessibility (a11y) Audit", category: "Frontend", tags: ["HTML", "a11y"], description: "Trova problemi di accessibilità nel markup HTML.", content: "Analizza questo HTML/JSX per problemi di accessibilità (WCAG 2.1 AA). Controlla: contrasto, label mancanti, ruoli ARIA, navigazione tastiera.\n\nCodice:\n[INCOLLA HTML]" },
    { id: 4, title: "TypeScript Interface Generator", category: "Frontend", tags: ["TypeScript", "JSON"], description: "Genera interfacce TS precise partendo da un oggetto JSON.", content: "Genera interfacce TypeScript da questo JSON. Usa PascalCase, `readonly` per ID, e `?` per campi opzionali. Estrai tipi nidificati.\n\nJSON:\n[INCOLLA JSON]" },
    { id: 5, title: "Framer Motion Animations", category: "Frontend", tags: ["React", "Animation"], description: "Crea animazioni fluide per componenti React.", content: "Scrivi un componente React usando Framer Motion che implementi una animazione di entrata (fade-in + slide-up) e una gestione delle gesture (hover/tap). L'animazione deve essere fluida e performante." },

    // --- BACKEND ---
    { id: 6, title: "Spiegazione Regex Complessa", category: "Backend", tags: ["Regex", "Utils"], description: "Spiegazione dettagliata di espressioni regolari.", content: "Spiega questa Regex passo passo. Dettaglia ogni gruppo di cattura e token. Fornisci 3 esempi di match positivi e 3 negativi.\n\nRegex: [INSERISCI REGEX]" },
    { id: 7, title: "Generatore Dati Mock SQL", category: "Backend", tags: ["SQL", "Database"], description: "Script SQL per popolare tabelle con dati realistici.", content: "Genera script SQL INSERT per popolare la tabella '[NOME_TABELLA]' con 20 righe di dati realistici. Colonne: [LISTA_COLONNE]. Gestisci chiavi esterne e formati data." },
    { id: 8, title: "Python Script Optimizer", category: "Backend", tags: ["Python", "Performance"], description: "Rendi il codice Python più 'Pythonic' e veloce.", content: "Ottimizza questo script Python. Usa List Comprehensions, generatori per grandi dati, e type hints. Riduci la complessità temporale.\n\nScript:\n[INCOLLA SCRIPT]" },
    { id: 9, title: "Node.js Controller Refactor", category: "Backend", tags: ["Node", "Express"], description: "Refactoring di un controller Express per separazione delle responsabilità.", content: "Riscrivi questo controller Express.js. Sposta la logica di business in un Service Layer separato. Implementa gestione errori async/await con try-catch o wrapper." },
    { id: 10, title: "Schema GraphQL da SQL", category: "Backend", tags: ["GraphQL", "API"], description: "Genera type definitions GraphQL da una struttura tabella.", content: "Basandoti su questa definizione di tabella SQL `CREATE TABLE`, genera il corrispondente Schema GraphQL (Type Def) e suggerisci i Resolver di base (Query/Mutation)." },

    // --- DEVOPS ---
    { id: 11, title: "Git Commit Formatter", category: "DevOps", tags: ["Git", "Workflow"], description: "Messaggi di commit semantici (Conventional Commits).", content: "Scrivi 3 opzioni di commit message (Conventional Commits) basati su questo `git diff`. Formato: `type(scope): description`." },
    { id: 12, title: "Docker Compose Creator", category: "DevOps", tags: ["Docker", "Infra"], description: "Crea file docker-compose per stack specifici.", content: "Crea un `docker-compose.yml` production-ready per: [Node.js, Postgres, Redis]. Includi volumi persistenti, reti, env_vars e limiti di risorse." },
    { id: 13, title: "GitHub Actions Pipeline", category: "DevOps", tags: ["CI/CD", "GitHub"], description: "Workflow per test e deploy automatico.", content: "Scrivi un workflow GitHub Actions che: 1) Faccia checkout codice. 2) Installi dipendenze (cache). 3) Esegua test unitari. 4) Se su main, esegua build docker e push su registry." },
    { id: 14, title: "Nginx Reverse Proxy", category: "DevOps", tags: ["Server", "Nginx"], description: "Configurazione sicura per Nginx.", content: "Genera una configurazione `nginx.conf` per agire da Reverse Proxy verso un'app su porta 3000. Includi: Redirect HTTP->HTTPS, Header di sicurezza, compressione Gzip." },
    { id: 15, title: "Terraform AWS S3", category: "DevOps", tags: ["Terraform", "AWS"], description: "Infrastructure as Code per bucket S3 sicuro.", content: "Scrivi codice Terraform per creare un bucket S3 privato. Blocca accesso pubblico, abilita versioning, abilita crittografia server-side (SSE-S3)." },

    // --- QUALITY ---
    { id: 16, title: "Unit Test Generator", category: "Quality", tags: ["Testing", "Jest"], description: "Crea test unitari completi per funzioni.", content: "Scrivi test Jest/Vitest per questa funzione. Copri: Happy path, Edge cases (null, vuoto), Gestione Errori. Mocka dipendenze esterne." },
    { id: 17, title: "Code Review Security", category: "Quality", tags: ["Security", "Review"], description: "Analisi critica focalizzata sulla sicurezza.", content: "Fai una security review di questo codice. Cerca: XSS, SQL Injection, dati sensibili esposti, validazione input debole. Suggerisci fix." },
    { id: 18, title: "API Documentation (Swagger)", category: "Quality", tags: ["Docs", "OpenAPI"], description: "Genera specifiche OpenAPI da codice route.", content: "Crea specifica OpenAPI (YAML) per questo endpoint API. Descrivi parametri path/query, body richiesta e risposte (200, 400, 500)." },
    { id: 19, title: "E2E Test Scenario (Cypress)", category: "Quality", tags: ["Testing", "Cypress"], description: "Scenari di test End-to-End per user flow.", content: "Scrivi un test Cypress per il flusso di 'Login Utente'. Step: visita pagina, compila form, click submit, verifica redirect dashboard e presenza cookie sessione." },
    { id: 20, title: "Bug Report Template", category: "Quality", tags: ["QA", "Management"], description: "Trasforma una descrizione vaga in un Bug Report formale.", content: "Riscrivi questa segnalazione vaga in un Bug Report professionale. Includi: Titolo chiaro, Precondizioni, Step to Reproduce, Risultato Atteso vs Attuale, Priorità." },

    // --- SOCIAL ---
    { id: 21, title: "LinkedIn Viral Hook", category: "Social", tags: ["LinkedIn", "Copywriting"], description: "Genera incipit accattivanti per post tecnici.", content: "Scrivi 5 'Hook' (frasi iniziali) per un post LinkedIn sull'argomento: '[INSERISCI ARGOMENTO]'. Lo stile deve essere: 2 controversi, 1 story-driven, 2 educativi. Obiettivo: fermare lo scroll." },
    { id: 22, title: "Storytelling da Codice", category: "Social", tags: ["Storytelling", "Personal Brand"], description: "Trasforma un problema tecnico in una storia.", content: "Trasforma la risoluzione di questo bug/problema tecnico in una breve storia per LinkedIn. Struttura: Il Problema (il dolore), Il Tentativo Fallito, L'Illuminazione (la soluzione), La Lezione imparata." },
    { id: 23, title: "Project Launch Post", category: "Social", tags: ["Marketing", "Launch"], description: "Annuncio professionale per nuovo progetto/portfolio.", content: "Scrivi un post LinkedIn per annunciare il lancio del mio nuovo progetto side-project: '[NOME PROGETTO]'. Descrivi: Problema che risolve, Stack tecnologico usato, Call to Action (link nei commenti). Tono: entusiasta ma professionale." },
    { id: 24, title: "Tech Contrarian Opinion", category: "Social", tags: ["Opinion", "Debate"], description: "Genera un'opinione argomentata su un trend.", content: "Aiutami a scrivere un post che esprime un'opinione impopolare o critica costruttiva su: '[TECNOLOGIA/TREND]'. Usa argomentazioni logiche, non odio. Struttura: 'Tutti amano X, ma ecco perché Y è meglio in questo caso'." },
    { id: 25, title: "Semplificazione Concetto", category: "Social", tags: ["Education", "Junior"], description: "Spiega concetti complessi a un pubblico misto.", content: "Spiega il concetto di '[CONCETTO TECNICO, es. Docker]' usando una metafora del mondo reale (non tecnica) per un post LinkedIn. Deve essere comprensibile anche ai recruiter o junior dev." },

    // --- IDEATION ---
    { id: 26, title: "SaaS Idea Generator", category: "Ideation", tags: ["Startup", "SaaS"], description: "Brainstorming di idee Micro-SaaS per nicchie.", content: "Agisci come un Product Manager. Genera 5 idee di Micro-SaaS B2B per la nicchia: '[NICCHIA, es. Dentisti, Ristoranti]'. Per ogni idea fornisci: Problema principale, Soluzione (MVP), Modello di pricing." },
    { id: 27, title: "Feature Naming", category: "Ideation", tags: ["Naming", "UX"], description: "Trova il nome perfetto per una nuova funzionalità.", content: "Sto creando una feature che fa: '[DESCRIZIONE]'. Genera 10 nomi possibili divisi per stile: 3 Descrittivi, 3 Astratti/Creativi, 3 Orientati all'azione. Il target è enterprise." },
    { id: 28, title: "Metodo SCAMPER", category: "Ideation", tags: ["Brainstorming", "Framework"], description: "Usa il framework SCAMPER per innovare un prodotto.", content: "Applica il metodo SCAMPER (Substitute, Combine, Adapt, Modify, Put to another use, Eliminate, Reverse) all'oggetto/app: '[OGGETTO]'. Genera una idea innovativa per ogni lettera dell'acronimo." },
    { id: 29, title: "User Persona Generator", category: "Ideation", tags: ["UX", "Design"], description: "Crea un profilo utente dettagliato per testare idee.", content: "Crea una User Persona dettagliata per un'app di '[TIPO APP]'. Includi: Nome, Età, Ruolo lavorativo, Obiettivi principali, Frustrazioni attuali (Pain points), Livello tecnologico." },
    { id: 30, title: "Devil's Advocate (Critique)", category: "Ideation", tags: ["Critique", "Strategy"], description: "Trova i punti deboli di un'idea prima di svilupparla.", content: "Agisci come un investitore scettico o 'Avvocato del Diavolo'. Analizza la mia idea: '[IDEA]'. Elenca 5 motivi critici per cui potrebbe fallire (es. competizione, costi, adozione) e poni 3 domande difficili a cui devo saper rispondere." },

    // --- STARTUP ---
    { id: 31, title: "Pitch Deck Structure", category: "Startup", tags: ["Funding", "Pitch"], description: "Struttura solida per una presentazione agli investitori.", content: "Crea una outline slide-by-slide per un Pitch Deck di una startup [SETTORE] in fase Seed. Per ogni slide (Problem, Solution, Market, Business Model, Team, Ask) scrivi 3 bullet point chiave che devono essere assolutamente presenti." },
    { id: 32, title: "Value Proposition Canvas", category: "Startup", tags: ["Strategy", "Product"], description: "Definisci chiaramente il valore del prodotto.", content: "Compila un Value Proposition Canvas per [PRODOTTO]. Elenca: 1) Customer Profile (Jobs to be done, Pains, Gains). 2) Value Map (Products & Services, Pain Relievers, Gain Creators). Assicurati che ci sia Product-Market Fit." },
    { id: 33, title: "Cold Email Investor", category: "Startup", tags: ["Outreach", "Email"], description: "Email fredda efficace per contattare Angel Investors.", content: "Scrivi una cold email breve (max 150 parole) indirizzata a un Angel Investor per presentare [NOME STARTUP]. Struttura: Hook personalizzato, 'The Problem', 'Our Solution' (con metriche di traction se presenti), e una Call to Action (CTA) soft per un meeting di 15 min." },
    { id: 34, title: "Competitor Analysis Matrix", category: "Startup", tags: ["Market", "Analysis"], description: "Analizza i competitor per trovare il vantaggio competitivo.", content: "Agisci come un Business Analyst. Crea una matrice di confronto per [LA TUA STARTUP] vs 3 Competitor principali ([NOME 1], [NOME 2], [NOME 3]). Confrontali su: Pricing, Feature Principali, Target Audience e Punti di Debolezza. Identifica il mio 'Unfair Advantage'." },
    { id: 35, title: "Go-To-Market Strategy", category: "Startup", tags: ["Marketing", "GTM"], description: "Piano di lancio per acquisire i primi utenti.", content: "Sviluppa una strategia Go-To-Market per lanciare [PRODOTTO] nei prossimi 3 mesi. Definisci: 1) Canali di acquisizione primari (es. LinkedIn, SEO, Cold Calling). 2) Strategia di contenuto. 3) KPI da monitorare. L'obiettivo è acquisire i primi 100 clienti paganti." }
];